### ISSUE TITLE
An "s" is being added to the file name of each import

### ISSUE THREAD

**Issue by rachelgli** [propublica/django-collaborative#6]
The original names were BRH and CAJails. (No spaces in either) 
![Screen Shot 2019-06-06 at 5 07 38 PM](https://user-images.githubusercontent.com/42387717/59066730-b9bd6f00-887d-11e9-99fc-452334a91da6.png)

**Comment by brandonrobertz** [comment]
Fixed. Now we just use the given data source name in all display scenarios.

**Comment by rachelgli** [comment]
It's still happening in my latest upload.
![Screen Shot 2019-07-08 at 5 26 10 PM](https://user-images.githubusercontent.com/42387717/60843747-82f0b680-a1a5-11e9-93e6-9adc794fd64d.png)
